"""SELF-IMPROVING pillar - the automated (but gated) half of it. Run once a month by
.github/workflows/monthly-retune.yml, on a fresh branch. Re-runs tune.py's safety-filtered sweep
against fresh Alpaca history, and IF a different combination now scores best AND it still passes
the exact same safety filter tune.py always applies, overwrites config/params.json on disk with
the proposal.

This script does NOT commit, push, merge, or otherwise touch the live bot - it only edits a file
in the workflow's local checkout. The GitHub Actions workflow that calls this script is what
turns that file edit into a pull request; nothing takes effect until a human reviews and merges
it. This is the guardrail called for in the project's design brief: the bot is allowed to learn
from accumulating history, but never allowed to change its own live risk/strategy behavior
without a person looking at a diff and a backtest report first.
"""
import json

from alpaca.data.historical import CryptoHistoricalDataClient

from config import PARAMS_PATH, load_params, load_settings
from tune import WINDOWS_TO_TEST, rank_safe_combos, sweep

SUMMARY_PATH = "retune_summary.md"
TUNED_KEYS = ["short_sma_window", "long_sma_window", "stop_loss_pct", "take_profit_pct", "min_confidence"]


def write_summary(text: str):
    with open(SUMMARY_PATH, "w") as f:
        f.write(text)


def main():
    base_settings = load_settings()
    data_client = CryptoHistoricalDataClient(base_settings.alpaca_api_key, base_settings.alpaca_secret_key)

    current_params = load_params()
    print(f"Current live parameters: {current_params}")

    results = sweep(base_settings, data_client)
    safe_results = rank_safe_combos(results)

    if not safe_results:
        print("No combination passed the safety filter this month - leaving config/params.json unchanged.")
        write_summary(
            "## Monthly retune: no proposal\n\n"
            "No parameter combination passed the safety filter (the drawdown/win-rate bar from "
            "tune.py) against this month's fresh data. config/params.json was left unchanged.\n"
        )
        return

    best = safe_results[0]
    sw, lw, sl, tp, mc, window_returns, window_drawdowns, window_winrates, window_buyhold = best
    proposed = dict(current_params)
    proposed.update({
        "short_sma_window": sw, "long_sma_window": lw,
        "stop_loss_pct": sl, "take_profit_pct": tp, "min_confidence": mc,
    })

    if all(current_params.get(k) == proposed[k] for k in TUNED_KEYS):
        print("Best safe combination is identical to the current live parameters - nothing to propose.")
        write_summary(
            "## Monthly retune: no change\n\n"
            "The best safety-filtered combination against this month's fresh data is identical "
            "to what's already live. config/params.json was left unchanged.\n"
        )
        return

    with open(PARAMS_PATH, "w") as f:
        json.dump(proposed, f, indent=2)
        f.write("\n")

    print("Wrote a new proposed config/params.json (not committed/pushed by this script).")
    for k in TUNED_KEYS:
        print(f"  {k}: {current_params.get(k)} -> {proposed[k]}")

    lines = [
        "## Proposed strategy parameter update (automated monthly retune)\n\n",
        "Generated by tune.py's safety-filtered parameter sweep, re-run against fresh historical "
        "data. This PR only changes config/params.json - nothing takes effect until it's "
        "reviewed and merged.\n\n",
        "| Parameter | Current | Proposed |\n|---|---|---|\n",
    ]
    labels = {
        "short_sma_window": "Short SMA window (hours)",
        "long_sma_window": "Long SMA window (hours)",
        "stop_loss_pct": "Stop-loss %",
        "take_profit_pct": "Take-profit %",
        "min_confidence": "Min confidence",
    }
    for k, label in labels.items():
        lines.append(f"| {label} | {current_params.get(k)} | {proposed[k]} |\n")

    lines.append("\n### Backtest results for the proposed combination\n\n")
    lines.append("| Window | Return | Buy & hold | Max drawdown | Win rate |\n|---|---|---|---|---|\n")
    for label, _ in WINDOWS_TO_TEST:
        lines.append(
            f"| {label} | {window_returns[label]:+.2f}% | {window_buyhold[label]:+.2f}% | "
            f"{window_drawdowns[label]:.2f}% | {window_winrates[label]:.1f}% |\n"
        )
    lines.append(
        "\n**Safety filter (held in every window above):** drawdown never worse than the "
        "configured limit, win rate never below the configured minimum - both set in tune.py. "
        "Return/buy-and-hold are shown for context and used to rank the winner, but are not "
        "themselves a pass/fail gate (see tune.py's module docstring for why).\n\n"
        "Review these numbers before merging - a good backtest is a hypothesis worth trying on "
        "paper, not a guarantee. Position size, total exposure, and daily-loss limits are never "
        "touched by this process - only you change those, directly in config/params.json.\n"
    )
    write_summary("".join(lines))


if __name__ == "__main__":
    main()
